name: Trigger workflow in other repo
on:
  push:
    branches:
      - master
jobs:
  trigger-scratch:
    runs-on: ubuntu-latest
    steps:
      - name: With Default Inputs
        env:
          PAT: ${{ secrets.SCRATCH_WORKFLOW_DISPATCH_PAT }}
        run: |
          curl -i -u ":$PAT" \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/tshowers-bt/scratch/actions/workflows/manual.yml/dispatches \
            -d '{
              "ref": "master"
            }'

      - name: With Default Inputs
        env:
          PAT: ${{ secrets.SCRATCH_WORKFLOW_DISPATCH_PAT }}
        run: |
          GIT_REF="${GITHUB_REF#refs/*/}"
          curl -i -u ":$PAT" \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/tshowers-bt/scratch/actions/workflows/manual.yml/dispatches \
            -d "{
              \"ref\":               \"$GIT_REF\",,
              \"inputs\": {
                \"api_branch\":      \"$GIT_REF\",
                \"frontend_branch\": \"$GIT_REF\",
                \"profile_branch\":  \"$GIT_REF\"
              }
            }"

